import type { ShowcaseEvent } from '../types';

export const SHOWCASE_EVENTS: ShowcaseEvent[] = [
  {
    event_name: 'Monsoon Onset 2022',
    request_date: '2022-06-25',
    lead_day: 3,
    variable: 'rainfall',
    event_type: 'active_break',
    description: 'Monsoon 2022 onset over Konkan coast — validation-window event.',
    data_source: 'live_model',
    mean_confidence: 66.1,
    mean_bust_probability: 0.275,
    top_drivers: [
      { rank: 1, channel_name: 'Seasonal phase', attribution_pct: 34.2, description: 'Winter/post-monsoon seasonal component' },
      { rank: 2, channel_name: 'Forecast precipitation pattern', attribution_pct: 32.6, description: 'Direct model precipitation forecast value' },
      { rank: 3, channel_name: 'Spatial position', attribution_pct: 12.0, description: 'Geographic longitude influence' },
    ],
  },
  {
    event_name: 'Peak Monsoon 2022',
    request_date: '2022-08-15',
    lead_day: 5,
    variable: 'rainfall',
    event_type: 'monsoon_depression',
    description: 'Active monsoon low-pressure system over Bay of Bengal and Odisha.',
    data_source: 'live_model',
    mean_confidence: 62.9,
    mean_bust_probability: 0.298,
    top_drivers: [
      { rank: 1, channel_name: 'Forecast precipitation pattern', attribution_pct: 39.5, description: 'Intense precipitation core over Odisha' },
      { rank: 2, channel_name: 'Seasonal phase', attribution_pct: 26.8, description: 'Monsoon seasonal component' },
      { rank: 3, channel_name: 'Lead time', attribution_pct: 15.2, description: 'Day 5 lead forecast spread' },
    ],
  },
  {
    event_name: 'Monsoon Onset 2021',
    request_date: '2021-06-15',
    lead_day: 5,
    variable: 'rainfall',
    event_type: 'active_break',
    description: 'Monsoon onset phase over Konkan & Goa / Odisha — first rains of 2021 season.',
    data_source: 'live_model',
    mean_confidence: 66.7,
    mean_bust_probability: 0.271,
    top_drivers: [
      { rank: 1, channel_name: 'Forecast precipitation pattern', attribution_pct: 32.4, description: 'Direct model precipitation forecast value' },
      { rank: 2, channel_name: 'Seasonal phase', attribution_pct: 29.9, description: 'Winter/post-monsoon seasonal component' },
      { rank: 3, channel_name: 'Lead time', attribution_pct: 11.4, description: 'Forecast lead horizon uncertainty accumulation' },
    ],
  },
  {
    event_name: 'Peak Monsoon 2021',
    request_date: '2021-08-10',
    lead_day: 5,
    variable: 'rainfall',
    event_type: 'monsoon_depression',
    description: 'Active monsoon phase — peak precipitation over Gangetic WB and Odisha.',
    data_source: 'live_model',
    mean_confidence: 64.8,
    mean_bust_probability: 0.285,
    top_drivers: [
      { rank: 1, channel_name: 'Forecast precipitation pattern', attribution_pct: 31.9, description: 'Direct model precipitation forecast value' },
      { rank: 2, channel_name: 'Seasonal phase', attribution_pct: 21.4, description: 'Winter/post-monsoon seasonal component' },
      { rank: 3, channel_name: 'Spatial position', attribution_pct: 16.5, description: 'Monsoon/summer seasonal component' },
    ],
  },
  {
    event_name: 'Monsoon Break 2021',
    request_date: '2021-09-15',
    lead_day: 7,
    variable: 'rainfall',
    event_type: 'active_break',
    description: 'Break phase — suppressed rainfall over peninsula, active over Himalayas.',
    data_source: 'live_model',
    mean_confidence: 64.5,
    mean_bust_probability: 0.287,
    top_drivers: [
      { rank: 1, channel_name: 'Seasonal phase', attribution_pct: 30.9, description: 'Monsoon/summer seasonal component' },
      { rank: 2, channel_name: 'Forecast precipitation pattern', attribution_pct: 29.7, description: 'Direct model precipitation forecast value' },
      { rank: 3, channel_name: 'Lead time', attribution_pct: 19.6, description: 'Forecast lead horizon uncertainty accumulation' },
    ],
  },
  {
    event_name: 'Cyclone Amphan (OOD Test)',
    request_date: '2020-05-16',
    lead_day: 4,
    variable: 'rainfall',
    event_type: 'cyclone',
    description: 'Super cyclonic storm Amphan pre-dating GEFSv12 archive — illustrative reference case.',
    data_source: 'illustrative_only',
    mean_confidence: 52.4,
    mean_bust_probability: 0.462,
    top_drivers: [
      { rank: 1, channel_name: 'Forecast precipitation pattern', attribution_pct: 45.0, description: 'Extreme rainfall core intensity' },
      { rank: 2, channel_name: 'Spatial position', attribution_pct: 32.0, description: 'Rapid track recurvature uncertainty' },
      { rank: 3, channel_name: 'Lead time', attribution_pct: 23.0, description: 'Non-linear intensification error' },
    ],
  },
];
